name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run update script
      env:
        GH_TOKEN: ${{ secrets.TOKEN }}
        user: ${{ secrets.USERNAME }}
      run: python main.py

    - uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'Update README'
        add: 'README.md'
